export enum JobName {
  TERMINATION = 'TERMINATION',
  INITIATION = 'INITIATION',
  CONFIGURATION = 'CONFIGURATION',
  AD_HOC_DELETE_PROCESS_INSTANCES = 'AD_HOC_DELETE_PROCESS_INSTANCES',
  AD_HOC_UPDATE_CASE_DATA = 'AD_HOC_UPDATE_CASE_DATA',
  AD_HOC_PENDING_TERMINATION_TASKS = 'AD_HOC_PENDING_TERMINATION_TASKS',
  TASK_INITIATION_FAILURES = 'TASK_INITIATION_FAILURES',
  TASK_TERMINATION_FAILURES = 'TASK_TERMINATION_FAILURES',
  TASK_CLEAN_UP = 'TASK_CLEAN_UP'
}
