export enum JobName {
  TERMINATION = 'TERMINATION',
  INITIATION = 'INITIATION',
  CONFIGURATION = 'CONFIGURATION',
  AD_HOC_DELETE_PROCESS_INSTANCES = 'AD_HOC_DELETE_PROCESS_INSTANCES',
  AD_HOC_CREATE_TASKS = 'AD_HOC_CREATE_TASKS'
}
