export enum JobName {
  TERMINATION = 'TERMINATION',
  INITIATION = 'INITIATION',
  CONFIGURATION = 'CONFIGURATION',
  AD_HOC_DELETE_PROCESS_INSTANCES = 'AD_HOC_DELETE_PROCESS_INSTANCES',
  AD_HOC_UPDATE_CASE_DATA = 'AD_HOC_UPDATE_CASE_DATA',
  AD_HOC_PENDING_TERMINATION_TASKS = 'AD_HOC_PENDING_TERMINATION_TASKS'
}
