s2s:
  microserviceName: wa_task_monitor
  secret: AAAAAAAAAAAAAAAA
  url: http://service-auth-provider-api
services:
  taskMonitor:
    url: http://localhost:8077
job:
  name: JOB_NAME
  camundaMaxResults: CAMUNDA_MAX_RESULTS
