apiVersion: v2
appVersion: "1.0"
description: A Helm chart for wa-task-batch-service App
name: wa-task-batch-service
home: https://github.com/hmcts/wa-task-batch-service
version: 0.0.13
dependencies:
  - name: job
    version: ~0.7.3
    repository: '@hmctspublic'



